# URL base para a API
base_url: https://serverest.dev

# URL para o Frontend
frontend_url: https://front.serverest.dev/

# Configurações de Navegador para testes de Frontend
browser: Chrome
headless: false  # true para rodar em modo headless

# Configurações de tempo de espera para testes
timeout: 10  # Tempo de espera padrão em segundos

# Configurações de API
api_timeout: 30  # Timeout para requisições da API
